"""Add views and likes to Post model

Revision ID: 6f920840c292
Revises: c03930cdaaaf
Create Date: 2025-03-27 19:29:21.197883 # Оставляем твою дату создания

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f920840c292'
down_revision = 'c03930cdaaaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем ТОЛЬКО новые колонки к ТАБЛИЦЕ post
    with op.batch_alter_table('post', schema=None) as batch_op:
        # Добавляем nullable=True и server_default='0' для совместимости со старыми записями
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=True, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True, server_default=sa.text('0')))

    # Важно: Устанавливаем значение по умолчанию для СУЩЕСТВУЮЩИХ строк, если они есть
    # Иначе колонка будет NULL, а не 0
    try:
        op.execute('UPDATE post SET views = 0 WHERE views IS NULL')
        op.execute('UPDATE post SET likes = 0 WHERE likes IS NULL')
        print("INFO: Set default 0 for views/likes on existing posts.")
    except Exception as e:
        print(f"INFO: Could not set default 0 for views/likes, possibly no posts exist yet: {e}")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем ТОЛЬКО добавленные колонки из ТАБЛИЦЫ post
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('likes')
        batch_op.drop_column('views')

    # ### end Alembic commands ###
